### PR TITLE
input: legacy encoding never encodes text for command mods on macOS

### LINKED ISSUE #5929: macOS: Cmd+H should not send "h" if its the last visible window
### Discussed in https://github.com/ghostty-org/ghostty/discussions/5870

<div type='discussions-op-text'>

<sup>Originally posted by **Samasaur1** February 19, 2025</sup>
On macOS, there are two easy shortcuts for hiding applications. Command-H hides the current application, while Option-Command-H hides all other applications. However, you must always have at least one unhidden application (enforced by the operating system). With all other apps, if the given app is the last unhidden app and you attempt to hide it with command-H, nothing happens. However, Ghostty handles the failing Command-H shortcut as a normal shortcut, which results in a normal `h` being sent to the terminal (when using the default config).

To reproduce:
- Make sure at least one Finder window is open (I'm not 100% sure this is necessary to reproduce, but hiding Finder behaves oddly when there are no windows)
- Open Ghostty
- Hide all other apps with Option-Command-H
- Attempt to hide Ghostty with Command-H
- Notice that you are typing `h`s into the terminal</div>

## Notes

I'm not sure how easy this is to fix, but we should match other application behavior in this case because `Cmd+H` is a system shortcut. I didn't do full research to see what other terminals do, but assuming Terminal.app and iTerm behave this way (h is not shown) we should do the same.

### PR DESCRIPTION
**Pull request by mitchellh**
Fixes #5929
Replaces #5984

On macOS, native applications typically never encode any text for key events that use the command key. This is because the command key is used for key equivalents and "commands" and should not be used for text input.

This can be verified with apps like TextEdit but also terminals like Terminal.app officially but also iTerm2 unofficially. Anything such as `Cmd+b` or `Cmd+Shift+b` will not produce any text input.

Cross-platform terminals generally don't follow this, for example Kitty performs CSI-u encoding and Alacritty and WezTerm encode the text as-is (i.e. `Cmd+b` will produce `b`).

On Linux, the super key (command-equivalent) does produce text input. For example, `Super+b` will produce `b` in Gnome Console, Foot, and all the cross-platform terminals mentioned above.

In the interest of matching the behavior of native macOS applications, we should not encode text for command key events on macOS. We continue to encode text for the super key on non-macOS platforms. This matches the behaviors appropriately on each platform.

### CODE REVIEW

File: src/input/KeyEncoder.zig [hunk 1]
```diff
@@ -413,6 +414,19 @@ fn legacy(
...
+    // don't in native text inputs (i.e. TextEdit) and they also don't
+    // in other native terminals (Terminal.app officially but also
+    // iTerm2).
+    //
+    // For Linux, we continue to encode text because it is typical.
+    // For example on Gnome Console Super+b will encode a "b" character
+    // with legacy encoding.
+    if ((comptime builtin.os.tag == .macos) and all_mods.super) {
+        return "";
+    }
```
Comment (mitchellh) [inline src/input/KeyEncoder.zig:428]: I will note that it is possible that this check is too late. We may want to omit ctrl sequence and other encodings as well when the super key is pressed on macOS. But the tests only cover this and this was the least-impacting change I could do with a very specific real world bug to verify it resolves. 

I'd be open to a broader change with a bit more research.

**Comment by rockorager** [comment]
Just so I understand... kkp encoding will still encode the associated text field when super + "b" is pressed? I am thinking we *shouldn't* do that and instead report it as no produced text...what do you think?

**Comment by mitchellh** [comment]
> Just so I understand... kkp encoding will still encode the associated text field when super + "b" is pressed? I am thinking we shouldn't do that and instead report it as no produced text...what do you think?

I can confirm it does not produce text, and the behavior matches Kitty.

**Review by rockorager — APPROVED** [review]
