### PR TITLE
Fix empty keybind setting

### LINKED ISSUE #5936: `keybind =` (blank) should restore default keybinds
### Discussed in https://github.com/ghostty-org/ghostty/discussions/5816

<div type='discussions-op-text'>

<sup>Originally posted by **levito** February 16, 2025</sup>
According to https://ghostty.org/docs/config#syntax, options with empty values should set them to the default. But with `keybind =`, all keybinds are removed, including the default ones.

Also, according to https://ghostty.org/docs/config#file-location, multiple config files are applied after one another, with the macOS config in `~/Library` overwriting the `~/.config` one.

With this behavior, I wanted to create two config files to have dotfiles working on both Linux and macOS:
1. `~/.config/ghostty/config` with options for both systems and keybinds for Linux
2. `~/Library/Application\ Support/com.mitchellh.ghostty/config` should then unset the Linux keybinds with `keybinds =` and set different ones for macOS

Did I miss anything, or is the current behavior that `keybind =` removes all keybinds including the default ones a bug?</div>

### PR DESCRIPTION
**Pull request by unknown**
Fixes https://github.com/ghostty-org/ghostty/issues/5936.

Extracts the default keybind setting to an `init` function. Add logic to call `init` in `parseIntoField` if it is defined for the type.

### CODE REVIEW

File: src/config/Config.zig [hunk 1]
```diff
@@ -5130,6 +5134,13 @@ pub const Keybinds = struct {
             return;
         }
 
+        if (std.mem.eql(u8, value, "")) {
```
Comment (unknown) [inline src/config/Config.zig:5137]: I didn't copy the above comment regarding clearing memory given the proximity but happy to copy it here if needed.

File: src/config/Config.zig [hunk 2]
```diff
@@ -1074,7 +1074,7 @@ class: ?[:0]const u8 = null,
 /// Ghostty will attempt to request these permissions. If the permissions are
 /// not granted, the keybind will not work. On macOS, you can find these
 /// permissions in System Preferences -> Privacy & Security -> Accessibility.
-keybind: Keybinds = .{},
```
Comment (jcollie) [inline src/config/Config.zig:1077]: All of the fields of `Config` should have a default value so that it can be instantiated as `.{}`.

File: src/config/Config.zig (hunk 1 above)
Comment (jcollie) [reply src/config/Config.zig:5137]: Just to be sure I'd copy it.

File: src/config/Config.zig [hunk 3]
```diff
@@ -5133,6 +5134,13 @@ pub const Keybinds = struct {
             return;
         }
 
+        if (std.mem.eql(u8, value, "")) {
+            log.info("config has 'keybind =', using default keybind", .{});
```
Comment (jcollie) [inline src/config/Config.zig:5138]: `keybind` at the end should be plural.

File: src/config/Config.zig (hunk 1 above)
Comment (jcollie) [reply src/config/Config.zig:5137]: A slight optimization would to be compare `value.len == 0`.

**Review by jcollie — CHANGES_REQUESTED** [review]

File: src/config/Config.zig (hunk 2 above)
Comment (unknown) [reply src/config/Config.zig:1077]: This requires thinking about how to change to [parseIntoField](https://github.com/unknown/ghostty/blob/5dc016e0d087439627c8816dd7d204e05074aa22/src/cli/args.zig#L238). The current logic is to use the default field value as a fallback when no value is provided. Not sure what the best option here would be.

Comment (jcollie) [reply src/config/Config.zig:1077]: Move `setDefaultKeybinds` to a method on `Keybinds` called `setToDefault`. In [`parseIntoFields`](https://github.com/unknown/ghostty/blob/5dc016e0d087439627c8816dd7d204e05074aa22/src/cli/args.zig#L254) check for that method with `@hasDecl` and call it instead of using the raw default value.

Comment (unknown) [reply src/config/Config.zig:1077]: Makes sense, thanks for the help!

**Review by jcollie — APPROVED** [review]

**Review by mitchellh — CHANGES_REQUESTED** [review]
One easy request. 

A couple notes for the future (we should NOT do them in this PR, just to keep things simple, but can follow up):

1. We should move the keybindings out to a dedicated file. They've been causing too much noise in `Config.zig` for too long and this reminded me. `src/config/keybinding.zig` or something.

2. We should make a `src/cli/args.init` function that takes a struct and uses comptime to find all the fields that have an `init` and call them so that we have one place we can always use to default any "config" structure (we use args for other stuff too).

File: src/cli/args.zig [hunk 4]
```diff
@@ -761,6 +767,29 @@ test "parseIntoField: ignore underscore-prefixed fields" {
...
+
+    var data: struct {
+        a: struct {
+            const Self = @This();
+
+            v: []const u8,
+
+            pub fn init(self: *Self, _alloc: Allocator) !void {
+                _ = _alloc;
+                self.v = "HELLO!";
```
Comment (mitchellh) [inline src/cli/args.zig:784]: FYI this isn't safe, you should be doing `self.* = .{ .v = "HELLO!" };`

**Review by mitchellh — CHANGES_REQUESTED** [review]
Apologies, one small thing. I'd fix it myself but not at a PC rn.

**Review by mitchellh — APPROVED** [review]

**Comment by mitchellh** [comment]
Perfect. Thanks!

**Comment by unknown** [comment]
> Apologies, one small thing. I'd fix it myself but not at a PC rn.



> Perfect. Thanks!

No worries! I can work on the followups when I get the chance.
