### PR TITLE
fix(gtk): add close confirmation for tabs

### LINKED ISSUE #4234: No confirmation when closing tab (GTK)
On the discord this bit of feedback came up from [here](https://ncurses.scripts.mit.edu/?p=ncurses.git;a=blob;f=misc/terminfo.src;h=ccd4c32099cf740d331eeaa3955f48f177435878;hb=a28a11d84d969cfdc876e158deae7870e8948a24#l8323)
```
8323 # - ghostty has tabs (imitating gnome-terminal); when closing a tab with a
8324 #   running process (e.g., a hung vttest), ghostty does not prompt about the 
8325 #   process to be killed.
```

On investigation there are two places in the GTK apprt where tabs are directly closed/removed without checking for confirmation/running processes ([1](https://github.com/ghostty-org/ghostty/blob/main/src/apprt/gtk/Tab.zig#L127), [2](https://github.com/ghostty-org/ghostty/blob/main/src/apprt/gtk/Tab.zig#L149))

### PR DESCRIPTION
**Pull request by leigholiver**
On the discord this bit of feedback came up from [here](https://ncurses.scripts.mit.edu/?p=ncurses.git;a=blob;f=misc/terminfo.src;h=ccd4c32099cf740d331eeaa3955f48f177435878;hb=a28a11d84d969cfdc876e158deae7870e8948a24#l8323)
```
8323 # - ghostty has tabs (imitating gnome-terminal); when closing a tab with a
8324 #   running process (e.g., a hung vttest), ghostty does not prompt about the 
8325 #   process to be killed.
```

This PR adds confirmation to the places where tabs are closed directly 

Fixes: https://github.com/ghostty-org/ghostty/issues/4234

### CODE REVIEW

File: src/apprt/gtk/Tab.zig [hunk 1]
```diff
@@ -121,10 +121,71 @@ pub fn remove(self: *Tab) void {
...
 
+/// Helper function to check if any surface in the split hierarchy needs close confirmation
+const needsConfirm = struct {
+    fn check(elem: Surface.Container.Elem) bool {
+        return switch (elem) {
+            .surface => |s| s.core_surface.needsConfirmQuit(),
+            .split => |s| check(s.top_left) or check(s.bottom_right),
+        };
+    }
+}.check;
```
Comment (mitchellh) [inline src/apprt/gtk/Tab.zig:132]: I'm aware of this pattern but its not something we generally do within this project.

I don't think we need to wrap this in a struct at all and can just make it a top-level (non-pub) `fn`.

**Comment by mitchellh** [comment]
Thanks! This only did GTK and didn't work for Adwaita builds. My add-on commit makes this work for Adwaita as well.
