### PR TITLE
cli: use sh to launch editor

### LINKED ISSUE #8898: `ghostty +edit-config` fails to use `$EDITOR` with arg
`ghostty +edit-config` should use the equivalent of (or maybe even just literally) `sh -c "$VISUAL ~/.config/ghostty/config` to launch an editor to edit the config from the CLI.

### Discussed in https://github.com/ghostty-org/ghostty/discussions/8896

<div type='discussions-op-text'>

<sup>Originally posted by **jamesboehmer** September 24, 2025</sup>
### Issue Description

When invoking `ghostty +edit-config`, the command fails because it cannot find the editor defined by `$VISUAL` or `$EDITOR`.  The command in question has an option with it, in my case `subl -w`, which opens a new Sublime Text window instead of adding a tab to an existing window.

### Expected Behavior

When running `ghostty +edit-config` from the command line it should open the config in `$VISUAL` or `$EDITOR`, e.g. `subl -w` or `vim -p`.

### Actual Behavior

Command fails

```
Failed to execute the editor. Error code=error.FileNotFound.

This is usually due to the executable path not existing, invalid
permissions, or the shell environment not being set up
correctly.

Editor: subl -w
Path: /Users/jim.boehmer/Library/Application Support/com.mitchellh.ghostty/config
```

### Reproduction Steps

1. Install `vim` or `Sublime Text`
2. export `VISUAL="vim -p"` or `VISUAL="subl -w"`
3. Run `ghostty +edit-config`

### Ghostty Logs

```text
Timestamp                       Thread     Type        Activity             PID    TTL
2025-09-24 14:24:46.560257-0400 0x8226d    Info        0x0                  48997  0    ghostty: [com.mitchellh.ghostty:default] ghostty version=1.2.0
2025-09-24 14:24:46.560836-0400 0x8226d    Info        0x0                  48997  0    ghostty: [com.mitchellh.ghostty:default] ghostty build optimize=ReleaseFast
2025-09-24 14:24:46.560862-0400 0x8226d    Info        0x0                  48997  0    ghostty: [com.mitchellh.ghostty:default] runtime=apprt.Runtime.none
2025-09-24 14:24:46.560877-0400 0x8226d    Info        0x0                  48997  0    ghostty: [com.mitchellh.ghostty:default] font_backend=font.main.Backend.coretext
2025-09-24 14:24:46.560889-0400 0x8226d    Info        0x0                  48997  0    ghostty: [com.mitchellh.ghostty:default] renderer=renderer.generic.Renderer(renderer.Metal)
2025-09-24 14:24:46.560904-0400 0x8226d    Info        0x0                  48997  0    ghostty: [com.mitchellh.ghostty:default] libxev default backend=kqueue
2025-09-24 14:24:46.561171-0400 0x8226d    Info        0x0                  48997  0    ghostty: [com.mitchellh.ghostty:os_locale] setlocale from env result=en_US.UTF-8
2025-09-24 14:24:46.561309-0400 0x8226d    Info        0x0                  48997  0    ghostty: [com.mitchellh.ghostty:default] executing CLI action=cli.ghostty.Action.edit-config
2025-09-24 14:24:46.561646-0400 0x8226d    Info        0x0                  48997  0    ghostty: [com.mitchellh.ghostty:default] reading configuration file path=/Users/jim.boehmer/.config/ghostty/config
2025-09-24 14:24:46.567098-0400 0x8226d    Info        0x0                  48997  0    ghostty: [com.mitchellh.ghostty:default] reading configuration file path=/Users/jim.boehmer/Library/Application Support/com.mitchellh.ghostty/config
2025-09-24 14:24:46.567193-0400 0x8226d    Info        0x0                  48997  0    ghostty: [com.mitchellh.ghostty:config] default shell source=env value=/bin/zsh
2025-09-24 14:24:46.568314-0400 0x8226e    Info        0x0                  48997  0    ghostty: [com.mitchellh.ghostty:sentry] sentry envelope does not contain crash, discarding
2025-09-24 14:24:46.581857-0400 0x4149e    Error       0x0                  3908   0    ghostty: [com.mitchellh.ghostty:stream] unimplemented OSC callback: terminal.osc.Command{ .end_of_command = terminal.osc.Command__struct_18672{ .exit_code = 1 } }
2025-09-24 14:24:46.582250-0400 0x4149e    Error       0x0                  3908   0    ghostty: [com.mitchellh.ghostty:stream] unimplemented OSC command: end_of_command
```

### Ghostty Version

```text
Ghostty 1.2.0

Version
  - version: 1.2.0
  - channel: stable
Build Config
  - Zig version   : 0.14.1
  - build mode    : builtin.OptimizeMode.ReleaseFast
  - app runtime   : apprt.Runtime.none
  - font engine   : font.main.Backend.coretext
  - renderer      : renderer.generic.Renderer(renderer.Metal)
  - libxev        : kqueue
```

### OS Version Information

MacOS Sequoia 15.7 Darwin FBG-GGV1W4GW2D 24.6.0 Darwin Kernel Version 24.6.0: Mon Aug 11 21:16:21 PDT 2025; root:xnu-11417.140.69.701.11~1/RELEASE_ARM64_T6000 arm64

### (Linux only) Display Server

None

### (Linux only) Desktop Environment/Window Manager

_No response_

### Minimal Ghostty Configuration

```ini
# n/a
```

### Additional Relevant Configuration

I believe this is just related to having the `VISUAL` or `EDITOR` env var value being used as the entire editor command, so it fails to find an editor named `subl -w`.  This works with generally every other command line tool, e.g. `git commit`.

### I acknowledge that:

- [X] I have reviewed the FAQ and confirm that my issue is NOT among them.
- [X] I have searched the Ghostty repository (both open and closed Discussions and Issues) and confirm this is not a duplicate of an existing issue or discussion.
- [X] I have checked the "Preview" tab on all text fields to ensure that everything looks right, and have wrapped all configuration and code in code blocks with a group of three backticks (` ``` `) on separate lines.</div>

### PR DESCRIPTION
**Pull request by jcollie**
Fixes #8898

### CODE REVIEW

File: src/cli/edit_config.zig [hunk 1]
```diff
@@ -133,13 +133,23 @@ pub fn run(alloc: Allocator) !u8 {
...
 
-    const editorZ = try alloc.dupeZ(u8, editor);
-    defer alloc.free(editorZ);
-    const pathZ = try alloc.dupeZ(u8, path);
-    defer alloc.free(pathZ);
+    var buf: std.ArrayListUnmanaged(u8) = .empty;
+    errdefer buf.deinit(alloc);
+
+    const writer = buf.writer(alloc);
+    var shellescape: internal_os.ShellEscapeWriter(std.ArrayListUnmanaged(u8).Writer) = .init(writer);
```
Comment (mitchellh) [inline src/cli/edit_config.zig]: I don't think we need to scape anything since it's being `exec` directly right? The shell isn't doing any argument parsing here.

**Review by mitchellh — CHANGES_REQUESTED** [review]

File: src/cli/edit_config.zig (hunk 1 above)
Comment (jcollie) [reply src/cli/edit_config.zig]: Escaping removed.

Comment (mitchellh) [reply src/cli/edit_config.zig]: Did you check if I was right? I wasn't 100% sure, but I'm pretty sure haha. Its worth checking.

Comment (jcollie) [reply src/cli/edit_config.zig]: Argh… Yeah now that I gave myself a few seconds to think. Yeah we need to escape the pathname in case it contains spaces or some other wierdness.
