### PR TITLE
fix: copy_url_to_clipboard copies full OSC8 URL instead of single cha…

### LINKED ISSUE #7499: `copy_url_to_clipboard` action doesn't work with links created with the OSC 8 escape sequence
### Discussed in https://github.com/ghostty-org/ghostty/discussions/7491

<div type='discussions-op-text'>

<sup>Originally posted by **lovelymono** May 31, 2025</sup>
### Issue Description

When creating a link using [OSC 8](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda) escape sequence, such as:

```sh
printf '\x1b]8;;https://mullvad.net\x1b\\this is a link\x1b]8;;\x1b\\\n'
```

or, if you're using fish shell:

```sh
printf '\x1b]8;;https://mullvad.net\x1b\\\\this is a link\x1b]8;;\x1b\\\\\n'
```

(the extra `\\` are needed to avoid fish interpreting `\\t` and `\\\n` as escape sequences) and trying to copy it with the `copy_url_to_clipboard` action bound to <kbd>ctrl</kbd>+<kbd>b</kbd>, only the character under the cursor is copied to clipboard, instead of the link.

I have the appropriate keybind in the Ghostty configuration file:

```
keybind = ctrl+b=copy_url_to_clipboard
```

### Expected Behavior

When pressing <kbd>ctrl</kbd>+<kbd>b</kbd> over `this is a link`, with mouse cursor over the character `l`, `https://mullvad.net` should be copied to the clipboard.

### Actual Behavior

Only the character `l` is copied to the clipboard.

### Reproduction Steps

1. Add `keybind = ctrl+b=copy_url_to_clipboard` to the Ghostty configuration file.
2. Run `printf '\x1b]8;;https://mullvad.net\x1b\\\\this is a link\x1b]8;;\x1b\\\\\n'` in the terminal.
3. Hover over the `this is a link` and press <kbd>ctrl</kbd>+<kbd>b</kbd>.
4. Paste the clipboard contents.

### Ghostty Logs

```text
info: ghostty version=1.1.3
info: ghostty build optimize=ReleaseFast
info: runtime=apprt.Runtime.gtk
info: font_backend=font.main.Backend.fontconfig_freetype
info: dependency harfbuzz=10.2.0
info: dependency fontconfig=21600
info: renderer=renderer.OpenGL
info: libxev backend=main.Backend.io_uring
info(os): setlocale from env result=en_US.UTF-8
info(gtk): GTK version build=4.18.5 runtime=4.18.5
info: reading configuration file path=/home/stella/.config/ghostty/config
info(config): default shell source=env value=/run/current-system/sw/bin/fish
warning(gtk): setting GDK_DEBUG=gl-no-fractional
warning(gtk): setting GDK_DISABLE=gles-api,vulkan
Unrecognized value "gl-no-fractional". Try GDK_DEBUG=help
info(gtk): libadwaita version build=1.7.2 runtime=1.7.2
info(grid): loaded OpenGL 4.6
info(io_exec): found Ghostty resources dir: /nix/store/8v707jcax8z4zxg370gkg4xak5j9hxcb-ghostty-1.1.3/share/ghostty
info(io_exec): shell integration automatically injected shell=termio.shell_integration.Shell.fish
warning(gtk): unimplemented action=apprt.action.Action.Key.cell_size
info(io_exec): started subcommand path=/bin/sh pid=63688
info(io_exec): subcommand cgroup=-
warning(gtk): unimplemented action=apprt.action.Action.Key.key_sequence
warning(gtk): unimplemented action=apprt.action.Action.Key.cell_size
warning(gtk): unimplemented action=apprt.action.Action.Key.key_sequence
warning(gtk): unimplemented action=apprt.action.Action.Key.cell_size
info(grid): reallocating GPU buffer old=0 new=8
warning(stream): unimplemented OSC callback: terminal.osc.Command{ .end_of_command = terminal.osc.Command.Command__struct_97811{ .exit_code = null } }
warning(stream): unimplemented OSC command: end_of_command
info(osc): unknown semantic prompts option: special_key
info(osc): unknown semantic prompts option: special_key
info(grid): reallocating GPU buffer old=8 new=105
info(osc): unknown semantic prompts option: cmdline_url
warning(stream): unimplemented OSC callback: terminal.osc.Command{ .end_of_command = terminal.osc.Command.Command__struct_97811{ .exit_code = 0 } }
warning(stream): unimplemented OSC command: end_of_command
warning(stream): unimplemented OSC callback: terminal.osc.Command{ .end_of_command = terminal.osc.Command.Command__struct_97811{ .exit_code = 0 } }
warning(stream): unimplemented OSC command: end_of_command
warning(stream): unimplemented OSC callback: terminal.osc.Command{ .end_of_command = terminal.osc.Command.Command__struct_97811{ .exit_code = null } }
warning(stream): unimplemented OSC command: end_of_command
info(osc): unknown semantic prompts option: special_key
info(osc): unknown semantic prompts option: special_key
warning(gtk): unimplemented action=apprt.action.Action.Key.key_sequence
warning(gtk): unimplemented action=apprt.action.Action.Key.key_sequence
info(grid): reallocating GPU buffer old=105 new=165
info(io_exec): pty fd closed, read thread exiting
info(surface): surface closed addr=560abf4d05a0

(process:57957): Gtk-CRITICAL **: 12:13:53.759: gtk_widget_unparent: assertion 'GTK_IS_WIDGET (widget)' failed
```

### Ghostty Version

```text
Ghostty 1.1.3

Version
  - version: 1.1.3
  - channel: stable
Build Config
  - Zig version: 0.13.0
  - build mode : builtin.OptimizeMode.ReleaseFast
  - app runtime: apprt.Runtime.gtk
  - font engine: font.main.Backend.fontconfig_freetype
  - renderer   : renderer.OpenGL
  - libxev     : main.Backend.io_uring
  - desktop env: gnome
  - GTK version:
    build      : 4.18.5
    runtime    : 4.18.5
  - libadwaita : enabled
    build      : 1.7.2
    runtime    : 1.7.2
  - libX11     : enabled
  - libwayland : enabled
```

### OS Version Information

NixOS (nixos-unstable 292fa7d4f651)

### (Linux only) Display Server

Wayland

### (Linux only) Desktop Environment/Window Manager

GNOME 48

### Minimal Ghostty Configuration

```ini
keybind = ctrl+b=copy_url_to_clipboard
```

### Additional Relevant Configuration

_No response_

### I acknowledge that:

- [X] I have reviewed the FAQ and confirm that my issue is NOT among them.
- [X] I have searched the Ghostty repository (both open and closed Discussions and Issues) and confirm this is not a duplicate of an existing issue or discussion.
- [X] I have checked the "Preview" tab on all text fields to ensure that everything looks right, and have wrapped all configuration and code in code blocks with a group of three backticks (` ``` `) on separate lines.</div>

### PR DESCRIPTION
**Pull request by AjStraight619**
fix: copy_url_to_clipboard for OSC8 hyperlinks

OSC8 links were only detected when exact platform-specific modifiers were held (Cmd on macOS, Ctrl on Linux), but copy_url_to_clipboard should work with either. Additionally, OSC8 links were using selectionString() which gets visible text instead of the actual URI. Now we use osc8URI() for OSC8 links and fall back to selectionString() for regex-detected links.

Fixes #7499

### CODE REVIEW

File: src/Surface.zig [hunk 1]
```diff
@@ -3280,7 +3280,7 @@ fn linkAtPos(
     const mouse_mods = self.mouseModsWithCapture(self.mouse.mods);
 
     // If we have the proper modifiers set then we can check for OSC8 links.
-    if (mouse_mods.equal(input.ctrlOrSuper(.{}))) hyperlink: {
+    if (mouse_mods.ctrl or mouse_mods.super) hyperlink: {
```
Comment (00-kat) [inline src/Surface.zig]: > but copy_url_to_clipboard should work with either

It actually doesn't work with either for non-OSC8 URLs:

https://github.com/user-attachments/assets/d3946452-34ed-45c7-842c-a094780a8682

```suggestion
    if (mouse_mods.equal(input.ctrlOrSuper(.{}))) hyperlink: {
```

**Review by 00-kat — APPROVED** [review]

File: src/Surface.zig (hunk 1 above)
Comment (mitchellh) [inline src/Surface.zig]: This logic isn't correct. 

We match `ctrl` on Linux and `super` on Mac. This changed this behavior.

File: src/Surface.zig [hunk 2]
```diff
@@ -3311,7 +3311,17 @@ fn linkAtPos(
...
+            .always_mods, .hover_mods => |v| {
+                // Special case: if the expected mods are "ctrl or super" (like the default URL config),
+                // then we should match if the user pressed either ctrl or super, just like OSC8 links.
+                const is_ctrl_or_super_expected = (v.ctrl and !v.super and !v.shift and !v.alt) or
+                    (v.super and !v.ctrl and !v.shift and !v.alt);
+                if (is_ctrl_or_super_expected) {
+                    if (!(mouse_mods.ctrl or mouse_mods.super)) continue;
+                } else {
+                    if (!v.equal(mouse_mods)) continue;
+                }
```
Comment (mitchellh) [inline src/Surface.zig]: I have no idea what's going on here, it's a boolean mess. We should pull this out into a tiny helper and write unit tests for it to clarify what we're trying to achieve.

File: src/Surface.zig [hunk 3]
```diff
@@ -4044,19 +4054,32 @@ pub fn performBindingAction(self: *Surface, action: input.Binding.Action) !bool
...
+                    },
+                    .open => url_text: {
+                        // For regex links, get the text from selection
+                        break :url_text (self.io.terminal.screen.selectionString(self.alloc, .{
+                            .sel = link_info[1],
+                            .trim = self.config.clipboard_trim_trailing_spaces,
+                        })) catch |err| {
+                            log.err("error reading url string err={}", .{err});
+                            return false;
+                        };
```
Comment (mitchellh) [inline src/Surface.zig:4506]: This stuff all looks good.

**Review by mitchellh — CHANGES_REQUESTED** [review]
Some stuff isn't right here.

**Comment by AjStraight619** [comment]
Thanks for the feedback. I will revert to using the old logic and will pull out the boolean logic and write some unit tests for it. Should have the PR updated by this weekend.

**Comment by mitchellh** [comment]
Thanks, no rush. Appreciate it.

**Comment by AjStraight619** [comment]
Hi Mitchel and Kat,

Sorry for the delay. I got caught up with the holiday weekend and work. Should have the updated changes pushed this weekend.

**Comment by AjStraight619** [comment]
Pushed up the fix for this. Turns out the boolean logic was not even needed to begin with! Let me know if anything else is needed.

**Review by 00-kat — APPROVED** [review]

**Review by mitchellh — APPROVED** [review]
This looks good, thanks for the cleanups. Looks much better to me. :)

**Comment by AjStraight619** [comment]
> This looks good, thanks for the cleanups. Looks much better to me. :)

No problem! Looking forward to contributing more.
