### PR TITLE
renderer: fix draw timer activation

### LINKED ISSUE #10667: Regression: GPU usage near 100% with Ghostty window being focused
### Discussed in https://github.com/ghostty-org/ghostty/discussions/10653

<div type='discussions-op-text'>

<sup>Originally posted by **onelocked** February 11, 2026</sup>
### Issue Description

I am experiencing high GPU usage when using Ghostty, I did git bisect and found that commit f85653414c9e was the culprit. Having the Ghostty window focused certainly spikes my gpu usage from idle at about 3-4% all the way up to 90-100%. The GPU usage is related to Ghostty window size, a smaller window reduces the GPU usage.

**Here is a screenshot of commit f85653414c9e and its GPU usage (I am using radeontop for gpu monitoring)**
image

**And this is a screenshot from commit 32f5677a9482. (its 1 commit below f85653414c9e)**
image

### Expected Behavior

Normal GPU usage.

### Actual Behavior

The GPU usage is extremely high.

### Reproduction Steps

1. Build Ghostty any rev above f85653414c9e.
2. Open Ghostty
3. Open a GPU monitoring tool (radeontop for example)
4. Make sure Ghostty window is focused.

### Ghostty Logs

_No response_

### Ghostty Version

```text
Ghostty 1.3.0-dev-f856534-nix

Version
  - version: 1.3.0-dev-f856534-nix
  - channel: tip
Build Config
  - Zig version   : 0.15.2
  - build mode    : .ReleaseFast
  - app runtime   : .gtk
  - font engine   : .fontconfig_freetype
  - renderer      : renderer.generic.Renderer(renderer.OpenGL)
  - libxev        : io_uring
  - kernel version: 6.18.8
  - desktop env   : other
  - GTK version   :
    build         : 4.20.3
    runtime       : 4.20.3
  - libadwaita    : enabled
    build         : 1.8.2
    runtime       : 1.8.2
  - libX11        : enabled
  - libwayland    : enabled
```

### OS Version Information

NixOS 26.05 (Yarara) x86_64

### (Linux only) Display Server

Wayland

### (Linux only) Desktop Environment/Window Manager

Niri (commit 41b5de87692b8262fbdbff7faab93f04ff0be453)

### Minimal Ghostty Configuration

```ini
Default config, my ~/.config/ghostty is empty.
```

### Additional Relevant Configuration

**My PC setup**
Mini-PC (Beelink EQR6)
CPU: AMD Ryzen 5 6600U (12) @ 4.59 GHz
GPU: AMD Radeon 680M [Integrated]

### I acknowledge that:

- [X] I have reviewed the FAQ and confirm that my issue is NOT among them.
- [X] I have searched the Ghostty repository (both open and closed Discussions and Issues) and confirm this is not a duplicate of an existing issue or discussion.
- [X] I have checked the "Preview" tab on all text fields to ensure that everything looks right, and have wrapped all configuration and code in code blocks with a group of three backticks (` ``` `) on separate lines.</div>

### PR DESCRIPTION
**Pull request by tobiaskohlbau**
The draw timer should only be activated in case a custom shader is configured and the option custom-shader-animation is either always or true. If the timer is kept alive CPU usage spiked enourmously.

Fixes #10667

### CODE REVIEW

File: src/renderer/Thread.zig [hunk 1]
```diff
@@ -295,21 +295,19 @@ fn setQosClass(self: *const Thread) void {
 fn syncDrawTimer(self: *Thread) void {
     skip: {
         // If our renderer supports animations and has them, then we
-        // always have a draw timer.
+        // can apply draw timer based on custom shader animation configuration.
```
Comment (tobiaskohlbau) [inline src/renderer/Thread.zig:298]: I still can't decide if keeping this solution of skipping is the most readable solution. It feels a bit wrapping your head around if something matches jump away, but that might be me not being used to that style of coding.

If maintainers have some suggestions to clean this up let me know :)

**Comment by MithicSpirit** [comment]
Can repro the issue, and this fixed it for me.
