### PR TITLE
fix: copy_title_to_clipboard respects user-overridden title

### LINKED ISSUE #10345: copy_title_to_clipboard copies original terminal title instead of manually renamed title
### Discussed in https://github.com/ghostty-org/ghostty/discussions/10344

<div type='discussions-op-text'>

<sup>Originally posted by **syy** January 16, 2026</sup>
### Issue Description

When using `copy_title_to_clipboard` action after renaming a tab with "Change Tab Title..." on macOS, the original terminal title is copied instead of the user-set renamed title.

The tab title renaming feature was added in February 2025 (#4217), and `copy_title_to_clipboard` was added in July 2025 (#7833). However, the copy action doesn't check for manually renamed titles. It only copies the original terminal title.

### Expected Behavior

When I rename a tab to "My Custom Tab" and then use copy_title_to_clipboard, the clipboard should contain "My Custom Tab".

### Actual Behavior

The clipboard contains the original terminal title (e.g., shell process name or current directory) instead of the renamed title.

### Reproduction Steps

1. Open Ghostty
2. Open Command Palette (Cmd+Shift+P or configured keybinding)
3. Search and select "Change Tab Title"
4. Enter a custom name like "My Custom Tab" and click OK
5. Open Command Palette again
6. Search and select "Copy Title to Clipboard"
7. Paste from clipboard (Cmd+V)
8. Observe: clipboard contains the original terminal title

### Ghostty Logs

_No response_

### Ghostty Version

```text
Ghostty 1.2.3

Version
  - version: 1.2.3
  - channel: stable
Build Config
  - Zig version   : 0.14.1
  - build mode    : builtin.OptimizeMode.ReleaseFast
  - app runtime   : apprt.Runtime.none
  - font engine   : font.main.Backend.coretext
  - renderer      : renderer.generic.Renderer(renderer.Metal)
  - libxev        : kqueue
```

### OS Version Information

macOS 26.2 (Build 25C56)

### (Linux only) Display Server

None

### (Linux only) Desktop Environment/Window Manager

_No response_

### Minimal Ghostty Configuration

```ini
bold-color = bright
shell-integration = zsh
split-divider-color = #282c34
theme = iTerm2 Dark Background
```

### Additional Relevant Configuration

_No response_

### I acknowledge that:

- [X] I have reviewed the FAQ and confirm that my issue is NOT among them.
- [X] I have searched the Ghostty repository (both open and closed Discussions and Issues) and confirm this is not a duplicate of an existing issue or discussion.
- [X] I have checked the "Preview" tab on all text fields to ensure that everything looks right, and have wrapped all configuration and code in code blocks with a group of three backticks (` ``` `) on separate lines.</div>

---

Note: We would likely need to move our surface/tab title override logic into Ghostty core to support this properly. Implementing this logic separately for both macOS and GTK is not only tedious but could also be quite error-prone.

### PR DESCRIPTION
**Pull request by Priyans-hu**
## Summary
- Fixes #10345 — `copy_title_to_clipboard` now copies the user-set custom title instead of the raw terminal title
- Adds a new `copy_title` apprt action as [suggested by @mitchellh](https://github.com/ghostty-org/ghostty/issues/10345#issuecomment-2601002974)
- Each platform (GTK + macOS) resolves the effective title (user override → terminal title fallback) before copying to clipboard

## Changes
- **`src/apprt/action.zig`** — New `copy_title` void action
- **`include/ghostty.h`** — C ABI enum entry
- **`src/Surface.zig`** — Binding handler now dispatches apprt action instead of inline logic
- **`src/apprt/gtk/class/surface.zig`** — `getEffectiveTitle()` helper (returns `title_override orelse title`)
- **`src/apprt/gtk/class/application.zig`** — GTK action handler
- **`macos/.../Ghostty.App.swift`** — macOS handler using `surfaceView.title` + `NSPasteboard`

*Note*: This PR was *AI* assisted.

### CODE REVIEW

File: include/ghostty.h [hunk 1]
```diff
@@ -904,6 +904,7 @@ typedef enum {
   GHOSTTY_ACTION_SEARCH_TOTAL,
   GHOSTTY_ACTION_SEARCH_SELECTED,
   GHOSTTY_ACTION_READONLY,
+  GHOSTTY_ACTION_COPY_TITLE,
```
Comment (jcollie) [inline include/ghostty.h]: Bikeshed: GHOSTTY_ACTION_COPY_TITLE_TO_CLIPBOARD

File: src/apprt/action.zig [hunk 2]
```diff
@@ -330,6 +330,11 @@ pub const Action = union(Key) {
     /// The readonly state of the surface has changed.
     readonly: Readonly,
 
+    /// Copy the effective title of the surface to the clipboard.
+    /// The effective title is the user-overridden title if set,
+    /// otherwise the terminal-set title.
+    copy_title,
```
Comment (jcollie) [inline src/apprt/action.zig]: Bikeshed: copy_title_to_clipboard

File: macos/Sources/Ghostty/Ghostty.App.swift [hunk 3]
```diff
@@ -647,6 +647,8 @@ extension Ghostty {
             case GHOSTTY_ACTION_SHOW_CHILD_EXITED:
                 Ghostty.logger.info("known but unimplemented action action=\(action.tag.rawValue)")
                 return false
+            case GHOSTTY_ACTION_COPY_TITLE:
```
Comment (jcollie) [inline macos/Sources/Ghostty/Ghostty.App.swift]: Bikeshed: GHOSTTY_ACTION_COPY_TITLE_TO_CLIPBOARD

File: src/apprt/gtk/class/application.zig [hunk 4]
```diff
@@ -649,6 +649,8 @@ pub const Application = extern struct {
             .close_tab => return Action.closeTab(target, value),
             .close_window => return Action.closeWindow(target),
 
+            .copy_title => return Action.copyTitle(target),
```
Comment (jcollie) [inline src/apprt/gtk/class/application.zig]: Bikeshed: copy_title_to_clipboard

File: src/apprt/gtk/class/application.zig [hunk 5]
```diff
@@ -1896,6 +1898,21 @@ const Action = struct {
         }
     }
 
+    pub fn copyTitle(target: apprt.Target) bool {
```
Comment (jcollie) [inline src/apprt/gtk/class/application.zig]: Bikeshed: copyTitleToClipboard

File: src/apprt/action.zig [hunk 6]
```diff
@@ -395,6 +400,7 @@ pub const Action = union(Key) {
         search_total,
         search_selected,
         readonly,
+        copy_title,
```
Comment (jcollie) [inline src/apprt/action.zig]: Bikeshed: copy_title_to_clipboard

File: src/Surface.zig [hunk 7]
```diff
@@ -5398,20 +5398,11 @@ pub fn performBindingAction(self: *Surface, action: input.Binding.Action) !bool
...
-            }}, false) catch |err| {
-                log.err("error copying title to clipboard err={}", .{err});
-                return true;
-            };
-
-            return true;
-        },
+        .copy_title_to_clipboard => return try self.rt_app.performAction(
+            .{ .surface = self },
+            .copy_title,
```
Comment (jcollie) [inline src/Surface.zig]: Bikeshed: copy_title_to_clipboard

**Comment by jcollie** [comment]
@Priyans-hu was any AI used in developing this PR? AI usage needs to be disclosed.

**Review by jcollie — CHANGES_REQUESTED** [review]
OK, some "minor" bikeshed comments. Otherwise the GTK & core code looks fine to me. I can't comment on the macOS-specific code.

Marking this as changes requested until I hear back about AI usage. PR description strongly suggests AI usage. Since there's an accepted issue AI usage is fine as long as it's disclosed.

**Comment by Priyans-hu** [comment]
Hi @jcollie , Thanks for quick review. Yes, AI (specifically @claude) was used to help across codebase exploration and quick understanding of flow.

**Comment by Priyans-hu** [comment]
Updated: copy_title -> copy_title_to_clipboard (and other similar references) @jcollie

**Comment by jcollie** [comment]
@Priyans-hu please update the PR description with a note about your AI usage.

**Comment by 00-kat** [comment]
For future reference: we have a strict [AI policy]; consider reading it before future contributions that involve AI usage!

[AI policy]: https://github.com/ghostty-org/ghostty/blob/main/AI_POLICY.md

File: src/apprt/gtk/class/application.zig [hunk 8]
```diff
@@ -1896,6 +1898,21 @@ const Action = struct {
         }
     }
 
+    pub fn copyTitleToClipboard(target: apprt.Target) bool {
+        return switch (target) {
+            .app => false,
+            .surface => |v| surface: {
+                const title = v.rt_surface.surface.getEffectiveTitle() orelse break :surface false;
```
Comment (jcollie) [inline src/apprt/gtk/class/application.zig]: This logic would be better as a function in `src/apprt/gtk/class/surface.zig`. See for example `desktopNotification` etc.

**Review by jcollie — APPROVED** [review]
One change, then the GTK side is good.

File: src/apprt/gtk/class/application.zig (hunk 8 above)
Comment (Priyans-hu) [reply src/apprt/gtk/class/application.zig]: Got your point, moved the logic to a function in surface file.

**Review by jcollie — APPROVED** [review]
LGTM

**Review by mitchellh — APPROVED** [review]

**Comment by jcollie** [comment]
!vouch
