### PR TITLE
fix canonicalizing some zh locales

### LINKED ISSUE #6870: macOS: Some zh locales are incorrectly canonicalized from BCP to POSIX
See #6865 and my associated comment.

We should special case `zh-Hans-CN` and `zh-Hant-TW` to `zh_CN` and `zh_TW` respectively.

### PR DESCRIPTION
**Pull request by Aaron-212**
resolve #6870

### CODE REVIEW

File: src/os/i18n.zig [hunk 1]
```diff
@@ -108,12 +108,15 @@ pub fn canonicalizeLocale(
     // Buffer must be 16 or at least as long as the locale and null term
     if (buf.len < @max(16, locale.len + 1)) return error.NoSpaceLeft;
 
+    // Fix zh locales for macOS
+    const updated = fixZHLocale(locale);
```
Comment (00-kat) [inline src/os/i18n.zig:112]: Pretty sure the Zig convention is to not full-caps acronyms.
>  Acronyms, initialisms, proper nouns, or any other word that has capitalization rules in written English are subject to naming conventions just like any other word. Even acronyms that are only 2 letters long are subject to these conventions. 
```suggestion
    const updated = fixZhLocale(locale);
```

File: src/os/i18n.zig [hunk 2]
```diff
@@ -123,6 +126,24 @@ pub fn canonicalizeLocale(
     return buf[0..slice.len :0];
 }
 
+fn fixZHLocale(locale: []const u8) []const u8 {
+    if (locale.len == 10 and std.mem.eql(u8, locale[0..2], "zh")) {
+        const script = locale[3..7];
+        const region = locale[8..10];
+
+        if (std.mem.eql(u8, script, "Hans")) {
+            if (std.mem.eql(u8, region, "SG")) return "zh-SG";
```
Comment (00-kat) [inline src/os/i18n.zig:135]: I don't really know this code or anything, but based on the description of #6870 I had thought these were meant to use underscores?

**Review by 00-kat — CHANGES_REQUESTED** [review]

**Review by pluiedev — CHANGES_REQUESTED** [review]

**Review by 00-kat — APPROVED** [review]

File: src/os/i18n.zig [hunk 3]
```diff
@@ -123,6 +126,24 @@ pub fn canonicalizeLocale(
...
+            if (std.mem.eql(u8, region, "SG")) return "zh_SG";
+            return "zh_CN";
+        } else if (std.mem.eql(u8, script, "Hant")) {
+            if (std.mem.eql(u8, region, "HK")) return "zh_HK";
+            if (std.mem.eql(u8, region, "MO")) return "zh_MO";
+            return "zh_TW";
+        }
+    }
+
+    return locale;
```
[the remark this answers is not in the document]
Comment (Aaron-212) [reply src/os/i18n.zig:144]: IMO it's okay because we're only dealing with `zh-Hans-CC` and `zh-Hant-CC`. Anything that doesn't match will just return the input locale. We can move on to more robust solutions later.

[the remark this answers is not in the document]
Comment (pluiedev) [reply src/os/i18n.zig:144]: It's just in general quite hard to read and isn't that much "shorter" than the alternative. Why write unmaintainable code when the maintainable version is about as complex?
```zig
var it = std.mem.splitScalar(u8, locale, '-');
const name = it.next() orelse return;
if (!std.mem.eql(u8, name, "zh")) return;

const script = it.next() orelse return;
const region = it.next() orelse return;

if (std.mem.eql(u8, script, "Hans")) {
	if (std.mem.eql(u8, script, "SG")) return "zh_SG";
	return "zh_CN";
} else if (std.mem.eql(u8, script, "Hant")) {
	if (std.mem.eql(u8, script, "MO")) return "zh_MO";
	if (std.mem.eql(u8, script, "HK")) return "zh_HK";
	return "zh_TW";
}
```

File: src/os/i18n.zig [hunk 4]
```diff
@@ -123,6 +126,26 @@ pub fn canonicalizeLocale(
     return buf[0..slice.len :0];
 }
 
+fn fixZhLocale(locale: []const u8) []const u8 {
```
Comment (pluiedev) [inline src/os/i18n.zig:129]: Add a doc comment explaining why (e.g. the libintl's internal canonicalize function returns erroneous results, etc)

File: src/os/i18n.zig [hunk 5]
```diff
@@ -108,12 +108,15 @@ pub fn canonicalizeLocale(
     // Buffer must be 16 or at least as long as the locale and null term
     if (buf.len < @max(16, locale.len + 1)) return error.NoSpaceLeft;
 
+    // Fix zh locales for macOS
+    const updated = fixZhLocale(locale);
```
Comment (pluiedev) [inline src/os/i18n.zig:112]: Is there even a point of canonicalizing via libintl for "fixed" zh locales? If not then we can possibly have something like this: (the return type would need to be changed to `?[:0]const u8`)
```suggestion
    if (fixZhLocale(locale)) |fixed| {
        return fixed;
    } else {
        // normal logic
    }
```

**Review by pluiedev — CHANGES_REQUESTED** [review]

**Review by pluiedev — APPROVED** [review]

**Review by mitchellh — CHANGES_REQUESTED** [review]
I'm going to make a couple small changes but thanks for tackling this.

**Review by mitchellh — APPROVED** [review]
