### PR TITLE
fix: quick terminal `focus-follows-mouse` behaviour

### LINKED ISSUE #3337: Quick Terminal - no 'focus-follows-mouse' functionality
Ghostty Version 1.0.0
Build 8469
Commit 4b4d4062

(MacOS)

I noticed when using splits in the Quick Terminal, `focus-follows-mouse = true` does not have an effect in the Quick Terminal. This may be working as intended though, and having focus follow inside splits inside the Quick Terminal is a pretty niche use case tbh.

### PR DESCRIPTION
**Pull request by dmehala**
# Description

Quick Terminal now focuses on the surface under the mouse pointer when `focus-follows-mouse` is enabled.

Fixes #3337

### CODE REVIEW

File: macos/Sources/Features/QuickTerminal/QuickTerminalWindow.swift [hunk 1]
```diff
@@ -1,6 +1,8 @@
 import Cocoa
 
 class QuickTerminalWindow: NSWindow {
+    var focusFollowsMouse: Bool = false
```
Comment (mitchellh) [inline macos/Sources/Features/QuickTerminal/QuickTerminalWindow.swift:4]: I think we should add this to `BaseTerminalController` and use that instead of a window property. That would simplify everything else in SurfaceView if we introduce new terminal types.

File: macos/Sources/Ghostty/SurfaceView_AppKit.swift [hunk 2]
```diff
@@ -617,12 +617,19 @@ extension Ghostty {
...
+                }
+            }()
+            
             // If focus follows mouse is enabled then move focus to this surface.
-            if let window = self.window as? TerminalWindow,
-               window.isKeyWindow &&
-                window.focusFollowsMouse &&
-                !self.focused
-            {
+            if (self.window!.isKeyWindow && !self.focused && focusFollowsMouse) {
```
Comment (mitchellh) [inline macos/Sources/Ghostty/SurfaceView_AppKit.swift:632]: I'd prefer to guard against window being null here. It is possible (we detach views at certain times).

File: macos/Sources/Features/QuickTerminal/QuickTerminalController.swift [hunk 3]
```diff
@@ -67,6 +67,9 @@ class QuickTerminalController: BaseTerminalController {
         // The quick window is not restorable (yet!). "Yet" because in theory we can
         // make this restorable, but it isn't currently implemented.
         window.isRestorable = false
+        
+        // Propagate `focus-follows-mouse` options to the quick terminal.
+        window.focusFollowsMouse = ghostty.config.focusFollowsMouse
```
Comment (mitchellh) [inline macos/Sources/Features/QuickTerminal/QuickTerminalController.swift:72]: BaseTerminalController has a windowDidLoad you can add this to. It might make sense to add a function there to call on config change too (notification is already there too).

**Review by mitchellh — CHANGES_REQUESTED** [review]

**Comment by mitchellh** [comment]
Appreciate this. 😄 Suggested some changes.

**Comment by dmehala** [comment]
I completely reverted https://github.com/dmehala/ghostty/commit/0ec402f926c66b2c94e217c18a30f55e36a5fe02 and addressed your comments. Now `BaseTerminalController` have a new `followFocusMouse` property which is used by `SurfaceView`. I'm not a Swift or AppKit expert, so this might not be the best approach 😅, but please feel free to take over if that works better for you.

File: macos/Sources/Features/Terminal/BaseTerminalController.swift [hunk 4]
```diff
@@ -62,6 +62,8 @@ class BaseTerminalController: NSWindowController,
 
     /// The configuration derived from the Ghostty config so we don't need to rely on references.
     private var derivedConfig: DerivedConfig
+    
+    private(set) var followFocusMouse: Bool = false
```
Comment (dmehala) [inline macos/Sources/Features/Terminal/BaseTerminalController.swift:66]:
```suggestion
    /// Keep track of whether the controller should focus on the pane currently being hovered.
    private(set) var followFocusMouse: Bool = false
```

**Comment by mitchellh** [comment]
Works great. Made some stylistic changes feel free to take a look. Will merge once green. Thanks

**Review by mitchellh — APPROVED** [review]
